apiVersion: v1
kind: Service
metadata:
  name: ibmcloud-service
spec:
  selector:
    app.kubernetes.io/name: ibmcloud
    type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

      nodePort: 30007